config/routes.rb
Rails.application.routes.draw do
  get 'posts/index'
  root 'posts#index'
  resources :posts do
    resources :comments
  end

  resources :categories do
    resources :comments
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :comments, as: :commentable, dependent: :delete_all
  has_many :posts, dependent: :destroy
  validates :name, presence: true, format: { with: /..{2}.*?\s..{2}.*?\.\z/,
             message: 'Вы неправильно ввели название категории, имя должно состоять с двух слов в конце точка. Пример: БМВ Е30.' }
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :commentable, polymorphic: true, dependent: :destroy
  validates :content, presence: true, alow_blank: false
  validates :author, presence: true, format: { with: /..{2}.*?\s..{2}.*?\.\z/ }
end

app/models/post.rb
class Post < ApplicationRecord
  paginates_per 4
  belongs_to :category
  has_many :comments, as: :commentable, dependent: :delete_all
  mount_uploader :image, ImageUploader
  validates :content, presence: { message: 'Заполните текст поста' }
  validates :name, presence: true, format: { with: /..{2}.*?\s..{2}.*?\./,
             message: 'Вы неправильно ввели название поста, имя должно состоять с двух слов в конце точка. Пример: БМВ Е30.' }
  validates :category_id, presence: { message: 'Выбирете категорию, если нет категорий, можете создать в разделе категории' }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:edit, :destroy, :show, :update]

  def new
    @category = Category.new
  end

  def destroy
    @comments = @category.comments
    @category.destroy
    @comments.destroy
    redirect_to categories_path
  end

  def index
    @categories = Category.all
  end

  def edit
  end

  def update
    if @category.update_attributes(category_params)
      redirect_to @category
    else
      render :edit
    end
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to @category
    else
      render :new
    end
  end

  def show
    @posts = @category.posts
  end

  private

  def set_category
    @category = Category.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:name, :description)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :load_commentable, only: [:create]
  def create
    @comment = @commentable.comments.create(params[:comment].permit(:author, :content, :commentable_type))
    @comment.save
    redirect_to @commentable
  end

  private

  def load_commentable
    resource, id = request.path.split('/')[1, 2]
    @commentable = resource.singularize.classify.constantize.find(id)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_posts, only: [:edit, :destroy, :show, :update]

  def new
    @post = Post.new
  end

  def destroy
    @comments = @post.comments
    @post.destroy
    @comments.destroy
    redirect_to posts_index_path
  end

  def index
    @posts = Post.order(:id).reverse_order.page
  end

  def edit
  end

  def update
    if @post.update_attributes(post_params)
      redirect_to @post
    else
      render :edit
    end
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to @post
    else
      render :new
    end
  end

  def show
  end

  private

  def set_posts
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:name, :content, :image, :category_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/categories/_form.html.erb
<% if @category.errors.any? %>
  <div class="alert alert-danger">
    <h5><%= 'Вы допустили ошибку при заполнении формы' %></h5>
    <ul>
      <% @category.errors.messages.each  do |attr, msg| %>
        <li><%= msg.to_s.gsub(/\["|"\]/, '') %></li>
      <%end%>
    </ul>
  </div>
<% end %>

<div class="container col-xl-8 col-lg-12  col-md-12 col-xs-1">
	<%= form_for @category do |f| %>
		<div class="form-group">
		  <%= f.label :Название_категории %><br>
		  <%= f.text_field :name, class: 'form-control', placeholder: 'BMW auto.' %><br>  
		</div>
		<div class="form-group">
		  <%= f.label :Описание_категории %><br>
		  <%= f.trix_editor :description, class: 'editor' %><br>  
		</div>
		<div class="form-group">
			<%= f.submit 'Cохранить категорию', class:'btn btn-info'%>
		</div>

	<% end %>
	<td><%= link_to 'Назад', categories_path %></td>
</div>

app/views/categories/edit.html.erb
<%= render 'form' %>

app/views/categories/index.html.erb
<%= link_to 'Новая категория', new_category_path %>

<section id="categories">
	<table class="table">
		<thead>
			<tr>
				<th>#</th>
				<th>Название</th>
			</tr>
		</thead>
		<tbody>
			<% @categories.each_with_index do |category, index|%>
				<tr>
					<td><%= index+1 %></td>
					<td><%= link_to category.name, category_path(category) %></td>
					<td>
						<%= link_to 'Изменить', edit_category_path(category), class:'btn btn-outline-primary btn-sm' %>
						<%= link_to 'Удалить', category_path(category), method: :delete, data: {confirm: 'Вы уверены? После удаления категории, будут удалены все статьи этой категории.' }, class:'btn btn-outline-danger btn-sm' %>
					</td>
				</tr>
			<% end %>
		</tbody>
	</table>

</section>

app/views/categories/new.html.erb
<%= render 'form' %>

app/views/categories/show.html.erb
<div class="container col-lg-12  col-md-12 col-xs-12">	
<h1><%= @category.name %></h1>
<p><%= @category.description.html_safe %></p>
	<div class="posts">
		<% @posts.each do |post| %>
			<div class="post">
				<h2><%= link_to post.name, post_path(post) %></h2>
				<% if post.image.present? %>
					<p class="img-post-index"> <img src="<%= post.image %>" alt=""> </p>
				<% end %>
				<p><%= post.content.length > 100 ? post.content.first(100).html_safe+'...' : post.content.html_safe   %></p> 
				<p><%= link_to 'Изменить пост' , edit_post_path(post) %></p>
			</div>
		<% end %>
	</div>
	<div class="comment_pane col-xl-12 col-lg-12  col-md-12 col-xs-12">
		<span>Коментарии:</span>
		<% @category.comments.each do |comment| %>
			<%= render 'comments/comment', comment: comment %>
		<% end %>
	</div> 	        

	<p>Добавить коментарий</p>

	<%= form_for([@category, @category.comments.build], remote: true) do |f| %>
		<div class="form-group">	
			<p><%= f.label 'Автор' %></p>
			<p><%= f.text_field :author, class:'form-control' %></p>
		</div>
		<div class="form-group">
			<p><%= f.text_area :content, class:'form-control' %></p> <br>
			<p><%= f.submit 'Создать коментарий', class:'btn btn-primary' %></p>	
		</div>
	<% end %>
</div>

app/views/comments/_comment.html.erb
<div class="comment_body">
	<p><%= comment.author %></p>
	<p><%= comment.content %></p>
</div>

app/views/comments/create.js.erb
$("#comment_pane").prepend("<%= j render @comment %>");
$("#comment_author").val('');
$("#comment_content").val('');

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blogm</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <header class="header">
    <ul class="menu nav">
      <li class="nav-item"><%= link_to 'Статьи', posts_path  %></li>
      <li class="nav-item"><%= link_to 'Категории', categories_path  %></li>
    </ul>
  </header>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<% if @post.errors.any? %>
  <div class="alert alert-danger">
    <h5><%= 'Вы допустили ошибку при заполнении формы' %></h5>
    <ul>
      <% @post.errors.messages.each  do |attr, msg| %>
        <li><%= msg.to_s.gsub(/\["|"\]/, '') %></li>
      <%end%>
    </ul>
  </div>
<% end %>

<div class="container col-xl-8 col-lg-12  col-md-12 col-xs-1">
	<%= form_for @post do |f| %>
		<div class="form-group">
		  <%= f.label :Название %><br>
		  <%= f.text_field :name, class: 'form-control', placeholder: 'BMW E30.' %><br>  
		</div>
		<div class="form-group">
		  <%= f.label :Текст %><br>
		  <%= f.trix_editor :content, class: 'editor' %><br>  
		</div>
		<div class="form-group">
		  <%= f.file_field :image %><br>
		</div>
		<div class="form-group">
			<%= f.label :Категория %><br>
			<%= f.collection_select :category_id, Category.order(:name), :id, :name, {include_blank: true}, class: 'form-control' %><br>  
		</div>
		<div class="form-group">
			<%= f.submit 'Cохранить', class:'btn btn-info'%>
		</div>

	<% end %>
<p><%= link_to 'Назад', posts_path, class:'btn btn-primary' %></p>
</div>

app/views/posts/edit.html.erb
<%= render 'form' %>

app/views/posts/index.html.erb
<div class="col-lg-12 col-xl-12 row">
	<h1><%= link_to 'Создать статью', new_post_path %></h1>
	<article class="posts col-xl-8 col-lg-8  col-md-12 col-xs-12">
		<% @posts.each do |post| %>
			<div class="post">
				<h2><%= link_to post.name.capitalize, post_path(post) %></h2>
				<p>(Статья опубликована: <time><%= post.created_at.to_date.strftime("%D %B , %Y") %></time>)</p>
				<% if post.image.present? %>
					<p class="img-post-index"> <img src="<%= post.image %>" alt=""> </p>
				<% end %>
				<p><%= post.content.length > 100 ? post.content.first(100).html_safe+'...' : post.content.html_safe   %></p> 
					<p><%= link_to 'Изменить статью', edit_post_path(post), class:'btn btn-info btn-sm' %> <%= link_to 'Удалить статью', post_path(post), method: :delete, data: {confirm: 'Вы уверены?'}, class:'btn btn-danger btn-sm' %></p>
			</div>
		<% end %>
	</article>
</div>
<div class="container">
		<%= paginate @posts %> <br>
</div>

app/views/posts/new.html.erb
<%= render 'form' %>

app/views/posts/show.html.erb
<div class="container">	
	<h2><%= @post.name.capitalize %></h2>
	<p><%= link_to 'Изменить статью', edit_post_path %> | <%= link_to 'Удалить', post_path, method: :delete, data: {confirm: 'Вы уверены?' } %></p>
	<p class="post-img"> <img src="<%= @post.image %>" alt=""> </p>
	<p><%= @post.content.html_safe %></p>

	<div class="comment_pane col-xl-12 col-lg-12  col-md-12 col-xs-12">
		<span>Коментарии:</span>
		<% @post.comments.each do |comment| %>
			<%= render 'comments/comment', comment: comment %>
		<% end %>
	</div> 	        

	<p>Добавить коментарий</p>

	<%= form_for([@post, @post.comments.build], remote: true) do |f| %>
		<div class="form-group">	
			<p><%= f.label 'Автор:' %>
			<%= f.text_field :author, class:'form-control', placeholder: 'Иванов Иван.' %></p>
		</div>
		<div class="form-group">
			<p><%= f.text_area :content, class:'form-control' %></p> <br>
			<p><%= f.submit 'Создать коментарий', class:'btn btn-primary' %></p>	
		</div>
	<% end %>
</div>	